<a href="https://colab.research.google.com/github/William-Ogilvie/Machine_Learning_Course/blob/main/Data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:, :-1].values # iloc is index locate
# this means all the rows and all the columns up to -1, so ignore the last column
# which is response varaible, -1 means index of last column, range in python includes
# lower bound but excluedes upper bound, so works, .values just means we take all the values
y = dataset.iloc[:, -1].values # gets the response vector which is the last column
# Or called dependent variable vector

# .values extracts the data as numpy arrays rather than a pd dataframe


In [ ]:
print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
# note the key colab commands:
# alt b is new cell below
# alb a is new cell above
# alt j is move to cell below
# alt k is move to cell above

In [ ]:
# we have two options for missing data: remove data or replace
# remove too many and u lose accuracy
# common to replace with things like the average, say for salary

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') # replace missing values by the mean
imputer.fit(X[:, 1:3]) # sets the imputer to the numeric columns and calcualtes the values, but doesn't apply
# thats what transform does
X[:, 1:3] = imputer.transform(X[:, 1:3]) # applys the imputer and returns the columns with
# nan replaced by means, update X


In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

In [ ]:
# Rather than number categorical, we do one hot encoding binary vectors for each
# of the countries, France = (1,0, 0), Spain = (0, 1, 0), Germany = (0, 0, 1)
# We can use numerics for binary outcomes, just don't want ordering for categorical

### Encoding the Independent Variable

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# transformers is the column u want to transformer and apply OneHotEncoder to remainder = 'passthrough' ensures we don't
# drop the other columns
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1) # so 20% in the test set
# generally u want more in the training set than test set, random_state fixes the seed

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

In [ ]:
# In multiple linear regression, the coefficients will adjust for the features
# magnitude

# Standarisation
# (x - \mu) / std(x), (-3, +3) normalises
# This works nearly all the time

# Normalisation
# x = (x - min(x)) / (max(x) - min(x))
# Recommended when normal distribution in features
# Obvs only take this in the x_train and x_test respectively

# So is recommeneded to do standardisation

# We do not need to standarise the dummy (indicator) variables, bc that makes no
# sense

from sklearn.preprocessing import StandardScaler

# Does standardisation
sc = StandardScaler()

# Fit only computes mean and standard deviation, transform applies this to the
# values

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) # ignore the one hot encoded values
X_test[:, 3:] = sc.transform(X_test[:, 3:])


# We need to apply the same transform method onto X_test, we shouldn't fit a new scalar
# bc then our data hasn't been scaled in the same way throwing off our predictions



In [ ]:
print(X_train)


[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)


[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
